import io
from datetime import datetime
from reportlab.lib.pagesizes import A4
from reportlab.lib import colors
from reportlab.lib.units import mm
from reportlab.pdfgen import canvas
from reportlab.platypus import Table, TableStyle


def generate_invoice(business_name: str, customer_name: str,
                     customer_phone: str, transactions: list,
                     balance: float) -> io.BytesIO:
    """Generate a PDF invoice and return as BytesIO buffer."""
    buffer = io.BytesIO()
    c = canvas.Canvas(buffer, pagesize=A4)
    width, height = A4

    # ── Header bar ────────────────────────────────────────────────────────────
    c.setFillColorRGB(0.25, 0.25, 0.60)
    c.rect(0, height - 80, width, 80, fill=True, stroke=False)

    c.setFillColor(colors.white)
    c.setFont("Helvetica-Bold", 22)
    c.drawString(30, height - 45, "📒 Digital Ledger")
    c.setFont("Helvetica", 11)
    c.drawString(30, height - 65, "Transaction Invoice")

    c.setFont("Helvetica", 10)
    c.drawRightString(width - 30, height - 45, f"Date: {datetime.now().strftime('%d %b %Y')}")
    c.drawRightString(width - 30, height - 60, f"Invoice #: INV-{datetime.now().strftime('%Y%m%d%H%M%S')}")

    # ── Customer info ─────────────────────────────────────────────────────────
    y = height - 110
    c.setFillColor(colors.black)
    c.setFont("Helvetica-Bold", 12)
    c.drawString(30, y, "Bill To:")
    c.setFont("Helvetica", 11)
    c.drawString(30, y - 18, customer_name)
    c.drawString(30, y - 34, f"Phone: {customer_phone}")

    c.setFont("Helvetica-Bold", 12)
    c.drawString(320, y, "From:")
    c.setFont("Helvetica", 11)
    c.drawString(320, y - 18, business_name)

    # ── Divider ───────────────────────────────────────────────────────────────
    y -= 60
    c.setStrokeColorRGB(0.25, 0.25, 0.60)
    c.setLineWidth(1.5)
    c.line(30, y, width - 30, y)

    # ── Table header ──────────────────────────────────────────────────────────
    y -= 25
    c.setFillColorRGB(0.25, 0.25, 0.60)
    c.rect(30, y - 5, width - 60, 22, fill=True, stroke=False)
    c.setFillColor(colors.white)
    c.setFont("Helvetica-Bold", 10)
    c.drawString(35,  y + 4, "Date")
    c.drawString(155, y + 4, "Type")
    c.drawString(275, y + 4, "Amount (₹)")
    c.drawString(390, y + 4, "Note")

    # ── Table rows ────────────────────────────────────────────────────────────
    y -= 20
    total_credit = 0.0
    total_paid   = 0.0
    row_num = 0

    for t in transactions:
        if y < 80:
            c.showPage()
            y = height - 50

        # Alternating row background
        if row_num % 2 == 0:
            c.setFillColorRGB(0.95, 0.95, 0.98)
            c.rect(30, y - 5, width - 60, 18, fill=True, stroke=False)

        date_str = t["date"].strftime("%d %b %Y") if hasattr(t["date"], "strftime") else str(t["date"])[:10]
        txn_type = "Credit" if t["type"] == "credit" else "Payment"
        amount   = t["amount"]

        if t["type"] == "credit":
            total_credit += amount
            c.setFillColor(colors.red)
        else:
            total_paid += amount
            c.setFillColor(colors.green)

        c.setFont("Helvetica", 9)
        c.setFillColor(colors.black)
        c.drawString(35,  y + 1, date_str)
        if t["type"] == "credit":
            c.setFillColorRGB(0.8, 0.1, 0.1)
        else:
            c.setFillColorRGB(0.1, 0.6, 0.1)
        c.drawString(155, y + 1, txn_type)
        c.setFillColor(colors.black)
        c.drawString(275, y + 1, f"₹{amount:,.2f}")
        c.drawString(390, y + 1, str(t.get("note", ""))[:22])

        y -= 18
        row_num += 1

    # ── Summary box ───────────────────────────────────────────────────────────
    y -= 20
    c.setStrokeColorRGB(0.25, 0.25, 0.60)
    c.setLineWidth(1)
    c.line(30, y, width - 30, y)

    y -= 20
    c.setFont("Helvetica-Bold", 11)
    c.setFillColor(colors.black)
    c.drawString(320, y,      f"Total Credit:   ₹{total_credit:,.2f}")
    c.drawString(320, y - 18, f"Total Paid:     ₹{total_paid:,.2f}")

    y -= 40
    c.setFillColorRGB(0.25, 0.25, 0.60)
    c.rect(300, y - 8, width - 330, 28, fill=True, stroke=False)
    c.setFillColor(colors.white)
    c.setFont("Helvetica-Bold", 13)
    c.drawString(310, y + 4, f"Outstanding Balance:  ₹{balance:,.2f}")

    # ── Footer ────────────────────────────────────────────────────────────────
    c.setFillColorRGB(0.5, 0.5, 0.5)
    c.setFont("Helvetica", 8)
    c.drawCentredString(width / 2, 30, "Generated by Digital Ledger • Thank you for your business!")

    c.save()
    buffer.seek(0)
    return buffer
